### ISSUE TITLE
Add external link function

### ISSUE THREAD

**Issue by sarahmwong** [dfe-analytical-services/shinyGovstyle#102]
Pinched from [dfe shiny](https://dfe-analytical-services.github.io/dfeshiny/reference/external_link.html)

External links often open in a new tab - need to warn users of this and protect them against any vulnerabilities that this exposes them to

**Comment by cjrace** [comment]
Think best way to do this is steal the code from dfeshiny, make sure to attach the CSS for govuk-link styling and have the function here. Then in dfeshiny we can update our package to just be a wrapper around `shinyGovstyle::external_link()` (that way we don't have two versions of the same code)
